### ISSUE TITLE
[Feature Request] Please include a way to make submit buttons

### ISSUE THREAD

**Issue by 10xchs** [heroui-inc/heroui#2322]
Just add `type` to the list of properties allowed to send to the Button component. It's kind of ridiculous that it's not implemented already.

**Comment by MNBoy** [comment]
@10xchs It's already there
<img width="511" alt="image" src="https://github.com/nextui-org/nextui/assets/57574386/caa4a840-0f4a-42cc-98cb-529998290cf0">
