### ISSUE TITLE
[BUG] - Documentation website scroll issue

### ISSUE THREAD

**Issue by withden** [heroui-inc/heroui#2707]
### NextUI Version

2.2.10

### Describe the bug

Hey, I just found a scrolling issue on the main page (nextui.org). I think it's not specific to any NextUI's version

On the main page, scroll down to the "Accessibility out of the box" section". Then you can't scroll down or flickering the screen when trying to scroll down. 

Please follow reproduce steps to reproduce the same issue in the following browsers
- Chrome (Latest stable build - Ubuntu 23.04)
- Opera (Latest stable build - Ubuntu 23.04)
- Chromium (Latest stable build - Ubuntu 23.04)

I also checked in Firefox, but I can't reproduce the same issue. 

### Steps to Reproduce the Bug or Issue

1. Go to nextui.org (main page)
2. Then go to any other page (/docs/components/avatar) or any other page
3. click on the logo (return to the main page 
4. then scroll down to the "Accessibility out of the box" section". Then you can't scroll down or flickering screen when trying to scroll down

I also provide video, if you need to reproduce the same issue

### Expected behavior

I expected smooth scrolling behavior on the main website.  

### Screenshots or Videos

Uploading Nextui-main-website-scrolling-issue.mp4…

### Operating System Version

Ubuntu 23.04 (Linux - Kernal 6.5.0-26-generic)

### Browser

Chrome

**Comment by wingkwong** [comment]
I can reproduce this issue on production doc website but not in `main` branch. Will put this on hold first and retry after the upcoming release.
