### ISSUE TITLE
[BUG] - `disableAnimation` prop not working in Button component

### ISSUE THREAD

**Issue by tovaschreier** [heroui-inc/heroui#3489]
### NextUI Version

@nextui-org/button@2.0.31

### Describe the bug

The button's `disableAnimation` prop should disable the rescaling animation on press. However, we currently need to add a `data-[pressed=true]:scale-100` class override as well in order to achieve that.

- I traced it to [this line](https://github.com/nextui-org/nextui/blob/canary/packages/core/theme/src/components/button.ts#L40) in the button component's source code, which seems to be getting applied even when we pass `disableAnimation`, likely due to [this change](https://github.com/nextui-org/nextui/pull/2929/files#diff-ae075221d59003e0b1c8add05fbb594132e2df8bd2d6b987f48aec5188166486L89)
- I believe that change accidentally broke the expected behavior of the `disableAnimation` prop, and would request that you re-disable the scaling behavior on press when `disableAnimation` is false.

### Steps to Reproduce the Bug or Issue

You can see it not working in [Storybook](https://storybook.nextui.org/?path=/story/components-button--disable-ripple&args=disableAnimation:!true). It seems like it removes the smooth transition but keeps the button resizing on press effect.

### Expected behavior

I would expect the button not to resize on press when `disableAnimation` is passed in.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by xndyz** [comment]
This is still an issue

**Comment by wingkwong** [comment]
@xndyz can you provide a video? I couldn't reproduce the issue.
