### ISSUE TITLE
New component : Sidebar

### ISSUE THREAD

**Issue by LeoBlouin** [heroui-inc/heroui#90]
Hi ! Congratulations for your work. I love NextUI and I think you have a very big potential.

I think a new component like navbar/sidebar should be great idea.

Something like this : [https://vuesax.com/docs/components/Sidebar.html#default](https://vuesax.com/docs/components/Sidebar.html#default)

**Comment by SellersEvan** [comment]
Sidebars and navbars would be a great addition. It would also be awesome to have bottom navbars for mobile web apps, and empty states. I saw another UI framework call these patterns, which I think is a great way to differentiate them from regular components.

**Comment by lindamacdonald** [comment]
Absolutely agree🙂

**Comment by salvowsky** [comment]
And maybe add some transition and different direction. Like Semantic UI do. I think it will be great with NEXTUI design😄 I'm excited to see all of the waitlist components release😁
[Sidebar - Semantic UI React](https://react.semantic-ui.com/modules/sidebar/#examples-transitions)
