### ISSUE TITLE
[BUG] - Clear button in input renders in top of text

### ISSUE THREAD

**Issue by notmedia** [heroui-inc/heroui#938]
### Describe the bug

<img width="361" alt="image" src="https://user-images.githubusercontent.com/12993018/205990017-ba1b7740-4d59-47fb-a582-cc66f91e966d.png">

### Steps to Reproduce the Bug or Issue

Type large text

### Expected behavior

Maybe we need to add margin here

### Operating System Version

macOS

### Browser

Chrome

**Comment by nooikko** [comment]
Looked into this a bit further to help with clarification.

Issue:
When utilizing `clearable` with the prop `contentLeft` the padding on the right side of the input is not respected. This appears to be due to `contentLeft` taking priority and removing the padding associated with `clearable`.

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2).

https://nextui.org/docs/components/input#clear-button
